source = ~/dotfiles/configs/hypr/monitors.conf
source = ~/dotfiles/configs/hypr/programs.conf
source = ~/dotfiles/configs/hypr/autostart.conf
source = ~/dotfiles/configs/hypr/env.conf
source = ~/dotfiles/configs/hypr/permissions.conf
source = ~/dotfiles/configs/hypr/look.conf
source = ~/dotfiles/configs/hypr/input.conf
source = ~/dotfiles/configs/hypr/keybinds.conf
source = ~/dotfiles/configs/hypr/rules.conf
